# Generated by Django 2.0 on 2018-09-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leakage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_url', models.TextField()),
                ('file_name', models.TextField()),
                ('file_url', models.TextField()),
                ('language', models.CharField(max_length=20)),
                ('code', models.TextField()),
                ('account', models.CharField(max_length=100)),
                ('account_avatar', models.TextField()),
                ('account_url', models.TextField()),
                ('status', models.IntegerField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('handle_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Leakage',
                'ordering': ('add_time',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(verbose_name='关键词')),
                ('pages', models.IntegerField(default=5, verbose_name='爬取页数')),
                ('interval', models.IntegerField(default=60, verbose_name='爬取间隔(分钟)')),
                ('status', models.IntegerField(choices=[(0, '等待中'), (1, '运行中'), (2, '完成')], default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('finished_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
            ],
        ),
    ]
