# Generated by Django 2.0 on 2018-09-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leakage',
            name='account',
        ),
        migrations.RemoveField(
            model_name='leakage',
            name='account_avatar',
        ),
        migrations.RemoveField(
            model_name='leakage',
            name='account_url',
        ),
        migrations.RemoveField(
            model_name='leakage',
            name='code',
        ),
        migrations.RemoveField(
            model_name='leakage',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='leakage',
            name='handle_time',
        ),
        migrations.RemoveField(
            model_name='leakage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='leakage',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='leakage',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='leakage',
            name='update_time',
        ),
        migrations.AddField(
            model_name='leakage',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='leakage',
            name='html_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='leakage',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='leakage',
            name='repo_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='leakage',
            name='repo_url',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='leakage',
            name='sha',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='leakage',
            name='user_avatar',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='leakage',
            name='user_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='leakage',
            name='user_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='leakage',
            name='file_name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='leakage',
            name='status',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '已处理'), (2, '白名单')], default=0),
        ),
    ]
