# Generated by Django 2.0 on 2018-09-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20180920_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='leakage',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.Task'),
        ),
    ]
