# Generated by Django 2.0 on 2018-10-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_leakage_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='leakage',
            name='fragment',
            field=models.TextField(default=''),
        ),
    ]
