# Generated by Django 2.0 on 2018-10-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='mail',
            field=models.TextField(default='', null=True, verbose_name='通知邮箱列表'),
        ),
    ]
