# Generated by Django 2.0 on 2018-10-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_task_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leakage',
            name='content',
        ),
    ]
