# Generated by Django 2.0 on 2019-10-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20181213_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='match_method',
            field=models.IntegerField(choices=[(0, '模糊匹配'), (1, '精确匹配'), (2, '正则匹配')], default=0),
        ),
    ]
